services:
  nextjs-app:
    image: conradkuklinsky/crossword-nextjs:{{sha}}
    restart: always

  nginx:
    image: conradkuklinsky/crossword-nginx-{{tier}}:{{sha}}
    restart: always
    ports:
      - "80:80"
    depends_on:
      - nextjs-app
