services:
  nextjs-app:
    image: conradkuklinsky/crossword-nextjs:1.0.0
    restart: always

  nginx:
    image: conradkuklinsky/crossword-nginx:1.0.1
    restart: always
    ports:
      - "80:80"
    depends_on:
      - nextjs-app
