services:
  nextjs-app:
    image: conradkuklinsky/crossword-nextjs:86441fb
    restart: always

  nginx:
    image: conradkuklinsky/crossword-nginx:86441fb
    restart: always
    ports:
      - "80:80"
    depends_on:
      - nextjs-app
