apiVersion: "postgresql.cnpg.io/v1"
kind: Cluster
metadata:
  name: postgres-main
spec:
  instances: 1
  storage:
    size: "10Gi"
    storageClass: "do-block-storage"

  resources:
    requests:
      memory: "128Mi"
      cpu: "100m" 
    limits:
      memory: "256Mi"
      cpu: "250m"

  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: "s3://conrad-crossword/postgres_backup/"
      endpointURL: "https://conrad-crossword.sfo3.digitaloceanspaces.com"
      s3Credentials:
        accessKeyId:
          name: spaces-cred-conrad-crossword
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: spaces-cred-conrad-crossword
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip

  bootstrap:
    initdb:
      database: crossword_db
      owner: crossword_db_user